### PR TITLE
Total Requests Code 

### PR DESCRIPTION
**Pull request by iavorque**
Howdy! I finished my code for total requests represented on the log file, please review and test the code to see if it works on your end. I've tested it on another Python editor, Spyder, and it outputted 726736 total requests, which should be accurate, however my VS Code continues to show syntax errors.

### CODE REVIEW

**Comment by Rvxannaduran** [comment]
I had a similar error as you did with syntax in VS code, but I used it in a different editor also and it ran perfectly fine!

**Comment by Rvxannaduran** [comment]
There appears to be one conflict with two repeated lines of code but removing them should solve the issue. The lines of code that appear to be repeated are the following: 
amt_request_total = 0
print("Total Amount of Requests for the total amount of time period:", amt_request_total)

**Review by Rvxannaduran — COMMENTED** [review]
There appears to be one conflict with two repeated lines of code but removing them should solve the issue.

**Comment by iavorque** [comment]
image
I finally got the previous code to run on my VS Code local machine successfully. Does my output match your screens? It should display amt_request_total as 726,736 which should be accurate but let me know if y'all find any problems either with the logic or syntax aspect.

**Comment by iavorque** [comment]
> 

Thanks! I removed the repeated lines of code since it said there was a conflict and just redid my code. No errors should be found now!

**Review by paulageronimo — APPROVED** [review]
Looks awesome! Thank you for doing this :)

**Comment by paulageronimo** [comment]
@clairek9 @texasaggie13 please go ahead and review this! It seems great, but do go ahead and test it out yourselves to see that there is no conflict and that it runs correctly

**Pull request merged**
