### PR TITLE
Fetching file

### PR DESCRIPTION
**Pull request by clairek9**
Hey everyone! Please review this for me. Any feedback is greatly appreciated.

### CODE REVIEW

**Comment by iavorque** [comment]
Looks good to me!

**Comment by paulageronimo** [comment]
I went ahead and tested it out and saw that it would overload the output. **I suggest removing lines 9 + 10 so it only displays faintly.** Other than that, great job 👏

**Review by paulageronimo — APPROVED** [review]
Looks good to me

**Review by iavorque — APPROVED** [review]
Great!

**Review by texasaggie13 — APPROVED** [review]
Looks good!

**Pull request merged**
